version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  backend:
    image: node:20
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: ["yarn", "backend"]

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - minio-volume:/data
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123

  redis: 
    image: redis:7.2-alpine
    ports:
      - 6379:6379

  mailhog: 
    platform: linux/amd64
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
volumes:
  postgres-data: {}
  minio-volume: {}