version: '3'

services:
  auth:
    image: classroom-go
    build: docker/development/go
    volumes:
      - ./go:/app/
    expose:
      - "${AUTH_SERVICE_PORT}"
    labels:
      - traefik.http.middlewares.auth.forwardauth.address=http://localhost/auth/
      - traefik.http.middlewares.auth.forwardauth.trustForwardHeader=true
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=X-Auth-User,X-Auth-User-Email"
      - traefik.http.routers.auth.rule=PathPrefix(`/auth`)
    command: ["air", "-c", "./config/.air.auth.toml"] 

  main:
    image: classroom-go
    build: docker/development/go
    volumes:
      - ./go:/app/
    expose:
      - "${MAIN_SERVICE_PORT}"
    labels:
      - traefik.http.routers.main.rule=PathPrefix(`/api`)
      - traefik.http.routers.main.middlewares=auth
    command: ["air", "-c", "./config/.air.classroom.toml"] 

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: classroom
    volumes:
      - classroom-postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0.1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: classroom
    volumes:
      - classroom-mongo:/data/db

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  traefik:
    image: traefik:2.4
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - minio-volume:/data
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123

  generate-docs:
    image: classroom-go
    build: docker/development/go
    volumes:
      - .:/app/
    working_dir: /app/go
    command: ["go", "run", "./cmd/auth", "docs:generate", "&&", "go", "run", "./cmd/classroom", "docs:generate"] 

volumes:
  classroom-postgres:
    external: false
  classroom-mongo:
    external: false
  minio-volume:
    external: false
